name: automation_accounts

on:
  push:
    branches:
        - main
  
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main

env:
  ARM_CLIENT_ID: #f1f5231e-ddde-4ba1-960e-915bd9319737 # dso-infra-azure-fixngo-devtest
  ARM_CLIENT_SECRET: ${{ secrets.DSO_AZURE_AUTOMATION_ACCOUNTS_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: b1f3cebb-4988-4ff9-9259-f02ad7744fcb # NOMS Dev & Test Environments
  ARM_TENANT_ID: 747381f4-e81f-4a43-bf68-ced6a1e14edf
  GITHUB_ORGANIZATION: ministryofjustice
  GITHUB_USERNAME: hmpps-dso-automation
  GITHUB_TOKEN: ${{ secrets.DSO_GITHUB_AUTOMATION_PAT }}
  WORKING_DIRECTORY: .

jobs:
  terraform:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GitHub credential.helper for terraform
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: https://${{ env.GITHUB_USERNAME }}:${{ env.GITHUB_TOKEN }}@github.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Terraform Action
        uses: ministryofjustice/terraform-action@v1.0.8
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          working-directory: ${{env.WORKING_DIRECTORY}}
